In [1]:
import numpy as np

Creating 2-d of zeroes  

In [2]:
arr = np.zeros((8, 4),dtype=np.int_)
for i in range(8):
    arr[i] = i
print(arr[2:5,:])


[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [3]:
matrix = np.array(range(32)).reshape(8,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [4]:
matrix.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [5]:
matrix.dot(matrix.T)


array([[  14,   38,   62,   86,  110,  134,  158,  182],
       [  38,  126,  214,  302,  390,  478,  566,  654],
       [  62,  214,  366,  518,  670,  822,  974, 1126],
       [  86,  302,  518,  734,  950, 1166, 1382, 1598],
       [ 110,  390,  670,  950, 1230, 1510, 1790, 2070],
       [ 134,  478,  822, 1166, 1510, 1854, 2198, 2542],
       [ 158,  566,  974, 1382, 1790, 2198, 2606, 3014],
       [ 182,  654, 1126, 1598, 2070, 2542, 3014, 3486]])

In [6]:
matrix.dot(matrix.T).shape

(8, 8)

## Pseudorandom Number Generation

In [7]:
from random import normalvariate
N = 1_000_000

In [8]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

703 ms ± 4.29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%timeit np.random.standard_normal(N)

27.6 ms ± 151 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3),dtype=np.float64)
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [11]:
data  = np.random.randint(0,20,7)
data

array([16, 17,  3, 18,  4, 10, 19])

In [12]:
x = rng.standard_normal(8)
print (x)
y = rng.standard_normal(8)
print (y)
np.maximum(x,y)

[-1.3677927   0.6488928   0.36105811 -1.95286306  2.34740965  0.96849691
 -0.75938718  0.90219827]
[-0.46695317 -0.06068952  0.78884434 -1.25666813  0.57585751  1.39897899
  1.32229806 -0.29969852]


array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In [13]:
points = np.arange(-5, 5, 1) # 100 equally spaced points
points

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [14]:
points.size

10

In [15]:
xs, ys = np.meshgrid(points, points)

In [16]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [17]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [18]:
ys.shape

(10, 10)

In [19]:
arr = rng.standard_normal((4, 4))
arr>0

array([[ True, False, False,  True],
       [False, False,  True,  True],
       [ True,  True, False, False],
       [False,  True,  True, False]])

In [20]:
outcome = np.where(arr>0,2,-2)
outcome

array([[ 2, -2, -2,  2],
       [-2, -2,  2,  2],
       [ 2,  2, -2, -2],
       [-2,  2,  2, -2]])

In [21]:
arr = np.array([[0, 1, 2], [-3, 4, 5], [6, 7, 8]])
arr

array([[ 0,  1,  2],
       [-3,  4,  5],
       [ 6,  7,  8]])

In [26]:
arr.cumsum(1)

array([[ 0,  1,  3],
       [-3,  1,  6],
       [ 6, 13, 21]])

In [27]:
arr.max(1)

array([2, 5, 8])

In [28]:
(arr>0).sum(0)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [29]:
(arr>0).sum(0)

array([1, 3, 3])