***Import all Packages ans datasets***  

In [23]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
iris = datasets.load_iris()

In [32]:
# print Sample data
x_input = iris["data"][:-10,3:]
x_output = (iris["target"][:-10] == 2).astype(np.int8)
x_test_input = iris["data"][-10:,3:]
x_test_pred_output = (iris["target"][-10:]== 2).astype(np.int8)


140


In [31]:
clf = LogisticRegression()
clf.fit(x_input,x_output)
print((x_test_input))
print(clf.predict(x_test_input))
print(x_test_pred_output)

[[2.4]
 [2.3]
 [1.9]
 [2.3]
 [2.5]
 [2.3]
 [1.9]
 [2. ]
 [2.3]
 [1.8]]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
